version: '3.8'
services:
  wem-dev:
    container_name: wem-dev
    build: .
    restart: unless-stopped
    entrypoint: "php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - db-dev
      - redis-dev
    ports:
      - "127.0.0.1:45060:8000"
    env_file: .env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db-dev
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: wemdev
      REDIS_HOST: redis-dev
    volumes:
      - ./app:/app/app

  db-dev:
    container_name: db-dev
    image: mariadb:10.3.32
    environment:
      MARIADB_DATABASE: laravel
      MARIADB_ROOT_PASSWORD: wemdev
    volumes:
      - db-dev_data:/var/lib/mysql

  redis-dev:
    container_name: redis-dev
    image: redis:alpine
    ports:
      - "6379:6379"

  laravel-echo-server:
    container_name: laravel-echo-server
    image: node:16
    working_dir: /app
    volumes:
      - ./app:/app
    command: "npm run echo-server"
    depends_on:
      - wem-dev
    ports:
      - "6001:6001"

volumes:
  db-dev_data:
